import 'package:flutter/material.dart';
import 'package:hexcolor/hexcolor.dart';

Color backgroundColor = HexColor("#FB6E3B");
Color accentColor = HexColor("#FB6E3B");
Color brownBackGroundColor = HexColor("#F4DBB2");
Color secondaryColor = HexColor("#FB6E3B");
Color primaryColor = HexColor("#FB6E3B");
// Color primaryColor = HexColor("#E65100");
Color grayColor1 = HexColor("#bebec7");

Color primaryColorDark = HexColor("#FB6E3B");
Color primaryColorDarkOne = HexColor("#FB6E3B");
Color primaryColors = HexColor("#FB6E3B");
Color primaryColorss = HexColor("#FB6E3B");
Color original = HexColor("#FF512F");
Color or = HexColor("#03041D");
Color orwhite = HexColor("#F8F8F8");
// Color accentColor = HexColor("#f85032");
Color textColor = HexColor("#686B78");
Color textColorCardTitle = HexColor("#47484d");
Color textColorSmall = HexColor("#93959F");
Color secondryColor = HexColor("#0074AD");
Color grayColor = HexColor("#E2E2E2");
Color grayColorOne = HexColor("#F4F4F5");
Color grayColors = HexColor("#8AE2E2E2");
Color darkGrayColor = HexColor("#717171");
Color blue = HexColor("#2a9d8f");
Color dark_blue = HexColor("#264653");
Color light_orange = HexColor("#f4a261");
Color orange = HexColor("#ff9130");
Color yellow = HexColor("#e9c46a");
Color blackColor = HexColor("#3E4152");
Color whiteColor = HexColor("#FFFAFA");
Color whiteColors = HexColor("#F2F6FC");
Color rose = HexColor("#fae1db");
Color counterButtonColor = HexColor("#ba8143");
Color chipBackgroundColor = HexColor("#ebebeb");
Color chipIcon = HexColor("#699153");
Color chipColor = HexColor("#f5f5f5");
Color chipSelectedColor = HexColor("#fcf0e8");
